- hosts: all
  tasks:
    - name: Include variables
      include_vars:
        file: variables.yml
    - name: Clean working directory
      file:
        path: "{{working_directory}}"
        state: absent
    - name: Copy sources
      copy:
        src: docker
        dest: "{{working_directory}}"
    - name: Download artifact
      get_url:
        url: https://github.com/KirillSmirnow/vpn-router/releases/download/v{{version}}/vpn-router-bootstrap-{{version}}.jar
        dest: "{{working_directory}}/docker"
    - name: Launch Docker Compose
      community.docker.docker_compose_v2:
        project_name: vpn-router
        project_src: "{{working_directory}}/docker"
        build: always
      environment:
        HEAP: "{{heap}}"
        SERVER_PORT: "{{public_port}}"
        SPRING_PROFILES_ACTIVE: "{{profiles}}"
        ALICE_SECRET: "{{alice.secret}}"
        ALICE_SKILL: "{{alice.skill}}"
        ALICE_USER: "{{alice.user}}"
        ALICE_APPLICATIONS: "{{alice.applications | join(',')}}"
        PRIVILEGED: true
        NETWORK_MODE: host
