services:
  app:
    build: .
    restart: always
    environment:
      HEAP:
      SERVER_PORT:
      SPRING_PROFILES_ACTIVE:
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 127.0.0.1:20100:8080
    volumes:
      - files:/root/vpn-router
volumes:
  files:
